import {StyleSheet} from 'react-native';
import {colorsTheme} from '../config/colorsTheme.js';

export const ButtonStyle = StyleSheet.create({
  buttonDefault: {
    backgroundColor: colorsTheme.button_green,
    alignItems: 'center',
    height: 50,
    width: '100%',
    marginTop: 30,
    justifyContent: 'center',
    borderRadius: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'RobotoMono-Medium',
    textAlign: 'center',
  },
  buttonWelcome: {
    backgroundColor: colorsTheme.button_green,
    alignItems: 'center',
    padding: 4,
    height: 50,
    width: 260,
    // marginTop: 30,
    justifyContent: 'center',
    borderRadius: 10,
  },
  buttonWelcome2: {
    backgroundColor: colorsTheme.button_green,
    alignItems: 'center',
    padding: 4,
    height: 50,
    width: 260,
    marginTop: 20,
    justifyContent: 'center',
    borderRadius: 10,
  },
  buttonDisplay: {
    backgroundColor: colorsTheme.button_green,
    alignItems: 'center',
    padding: 4,
    height: 50,
    width: '90%',
    marginTop: 20,
    justifyContent: 'center',
    borderRadius: 10,
    fontFamily: 'RobotoMono-Medium',
  },
  buttonDisplayRed: {
    backgroundColor: 'red',
    alignItems: 'center',
    padding: 4,
    height: 50,
    width: '90%',
    marginTop: 20,
    justifyContent: 'center',
    borderRadius: 10,
  },
  connect: {
    color: 'white',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 18,
    marginHorizontal: 40,
    marginVertical: 10,
    height: 40,
    margin: 6,
    padding: 10,
    borderRadius: 5,
  },
  connectWelcome: {
    textAlign: 'center',
    color: colorsTheme.txt_white,
    fontSize: 16,
    fontFamily: 'RobotoMono-Bold',
  },
});
